WICG/serial

index.html

Detailed discussions are in #25, #20, #19, #4.
* Defined how requestPorts() method works
* defined how getInfo() works
* made SerialPortInfo into a map (was SerialPortDetails)
* introduced the concept of "recommended serial port metadata"
* defined the rules for "getting serial port metadata"
* Updated the security considerations section.

Define how ports are requested (closes #25, #20, #19, #4)

---

CONTRIBUTING.md
README.md
respecConfig.js

These references have been updated to point at the Web Platform Incubator CG instead.

Update remaining references to WHATWG and Web of Sensors CG

---

index.html

The interfaces provide a `serial` attribute that is the entrypoint to the API. The getPorts() and requestPort() methods replace the SerialPort constructor in order to avoid exposing the raw serial port path to script. The Serial interface also provides events that can be fired when a port is added or removed from the system as will be the case for USB based serial devices.

Introduce Navigator and WorkerNavigator partial interfaces

---

index.html

:wave: Hello,
Not sure if this was intentional or not, but `productId` is listed twice in the port metadata table. This is a tiny PR to remove one of the instances of it.
Thanks 🙇

remove duplicated productId prop from metadata table

---

EXPLAINER.md

This change expands the examples to more gradually introduce concepts such as locked streams and transforms.

Add detail to stream usage examples

---

index.html

Probably respec issue, but removing the new lines fixes it

Make ParityType enum description render properly

---

EXPLAINER.md
index.html

This patch renames the properties of the SerialOptions dictionary so
that they are in lowerCamelCase, as is typical of other web platform
APIs.
The boolean flow control parameters have been simplified into a
FlowControlType enum. Support for configuring software flow control
(XON/XOFF) is removed until more implementation experience has been
gathered.
Fixes #93.

Rename fields to use lowerCamelCase

---

index.html
respecConfig.js

This change is a large rewrite of the Serial API with some notable
changes:
* The specification is renamed to the Web Serial API.
* All interface attributes and methods have algorithmic steps.
* Examples from the explainer have been integrated.
* The Security and Privacy considerations sections have been expanded.

Rewrite specification with algorithms and expanded examples

---

index.html

This change clarifies why port.close() is being called at the end of
the readUntilClosed() function and not after calling reader.cancel().
A line is added to wait until readUntilClosed() finishes to provide an
example of how to wait until the port is closed.
Fixes #113.

Clarify the example of exiting a read loop

---

index.html

Rather than setting "ringIndicator" and "dataSetReady" the steps reset "dataCarrierDetect" two more times.
Fixes #118.

Fix copy-paste error in getSignals() algorithm

---

index.html

When the user does not select a port Chromium throws a `NotFoundError`, not an `AbortError`.

requestPort() throws a NotFoundError

---

index.html

ReSpec has been updated to require a reference to the interface defining an internal slot.
Fixes #143.

Reference interface name in internal slots

---

index.html

Fixes ReSpec errors. Recent change to ReSpec mandates that internal slots must be "for" something explicitly.

Editorial: associate slots with interface

---

index.html

`SerialConnectionEvent` doesn't exist anymore, so there should be no `e.port`.

e.port -> e.target

---

index.html

When controller.signal is aborted, abort the current write operation so that the stream can close more quickly.
Partially resolves #152.

Listen for AbortSignal in writeAlgorithm

---

index.html

Following https://github.com/WICG/webhid/pull/84 and https://github.com/WICG/webusb/pull/214, this PR is an attempt to provide a way for web developers to revoke permission access to a paired SerialPort.
```js
// Request a serial port.
const port = await navigator.serial.requestPort();
// Then later... revoke permission to the serial port.
await port.forget();
```
@reillyeon Please have a look
FIX: #132

Add SerialPort.forget() method

---

index.html

This PR makes sure `requestPort()` fails if filter contains both bluetooth and usb members. This matches [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/serial/serial.cc;l=164;drc=9ed4a90ee6aeaa3c1911d229dec6317d8fe8260d).
```cpp
if (filter->hasBluetoothServiceClassId()) {
if (filter->hasUsbVendorId() || filter->hasUsbProductId()) {
exception_state.ThrowTypeError(
"A filter cannot specify both bluetoothServiceClassId and "
"usbVendorId or usbProductId.");
return nullptr;
}
```
@nondebug @reillyeon Please review.

Fail if filter contains both bluetooth and usb members

---

EXPLAINER_BLUETOOTH.md

Add an example for using `SerialPort.connected` per request from https://groups.google.com/a/chromium.org/g/blink-dev/c/KPN62vo5Pp4/m/Kc8tkB1eAAAJ.

An example of using SerialPort.connected

---

index.html

The example needs to explain how to use the Promise returned by pipeTo() to wait for the port to be closable.
Fixed #209.

Update example of creating a pipe chain on readable

---

index.html

From examples in other specifications it seems that the correct way to return a dictionary is to create an ordered map, for which we can either build it incrementally or by using the literal syntax.

Create dictionary return values as ordered maps
